
INPUT:
  MAX_SIZE_TEST: 1024
MODEL:
  ROI_BOX_HEAD:
    NUM_FC: 2
  ROI_HEADS:
    NAME: "StandardROIHeads"
    SCORE_THRESH_TEST: 0.5
DATASETS:
  TRAIN: ("sample_fashion_train", )
  TEST: ("sample_fashion_test",)
SOLVER: 
  MAX_ITER: 500
  IMS_PER_BATCH: 4
  BASE_LR: 0.004
OUTPUT_DIR: '/home/julien/data-science/kaggle/imaterialist/output/images'
